### ISSUE TITLE
Missing virtualbox guest additions on puppetlabs/debian-7.6-64-nocm

### ISSUE THREAD

**Issue by mnencia** [puppetlabs/puppetlabs-packer#23]
I've just tried the puppetlabs/debian-7.6-64-nocm image, and vagrant complaints about the lack of virtualbox guest additions on the box. Because of that it is unable to mount any directory.

**Comment by heathseals** [comment]
The guest additions work properly on debian-7.8 which is available on [Atlas](https://atlas.hashicorp.com/puppetlabs).

```
==> default: Waiting for HGFS kernel module to load...
==> default: Enabling and configuring shared folders...
    default: -- /Users/heath/Downloads: /vagrant
✔ ~/Downloads
22:40 $
```
