### ISSUE TITLE
Cannot resolve DNS on CentOS 5.11 after first boot

### ISSUE THREAD

**Issue by 3flex** [puppetlabs/puppetlabs-packer#33]
This seems to only affect CentOS 5.11 (6 and 7 are OK). After first boot this is in `/etc/resolv.conf`:

```
search delivery.puppetlabs.net
nameserver 10.240.0.10
nameserver 10.240.1.10
```
This prevents DNS lookups from working in beaker after the initial boot as I'm using a base setup of VirtualBox and Vagrant and there are no DNS servers listening on those IPs.

The nameservers should be coming from DHCP instead.

**Comment by heathseals** [comment]
This has been resolved in more recent boxes
```
22:24 $ vagrant ssh
[vagrant@localhost ~]$ cat /etc/resolv.conf
; generated by /sbin/dhclient-script
search localdomain
nameserver 172.16.177.2
[vagrant@localhost ~]$
```
