### ISSUE TITLE
Centos 7 sshd_config uses the incorrect path to sftp-server

### ISSUE THREAD

**Issue by deployable** [puppetlabs/puppetlabs-packer#40]
File: `/etc/ssh/sshd_config`

    Subsystem sftp /usr/lib/openssh/sftp-server

Doesn't exist

    [vagrant@localhost ~]$ ls -l /usr/lib/openssh/sftp-server
    ls: cannot access /usr/lib/openssh/sftp-server: No such file or directory

Should be 

    [vagrant@localhost ~]$ ls -l /usr/libexec/openssh/sftp-server
    -rwxr-xr-x. 1 root root 70176 Jun 10  2014 /usr/libexec/openssh/sftp-server

**Comment by beniji** [comment]
Yep I found this too - would be good to get this fixed

**Comment by ThoMo** [comment]
+1

**Comment by tmehlinger** [comment]
+1

**Comment by deployable** [comment]
https://github.com/puppetlabs/puppetlabs-packer/pull/43

**Comment by heathseals** [comment]
This was fixed in #51 and updated CentOS 7.2 boxes have been published to [Atlas](https://atlas.hashicorp.com/puppetlabs).
